from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from textwrap import wrap
from datetime import datetime


def draw_wrapped_text(c, text, x, y, max_width, line_height):
    """
    Helper function to wrap long text properly
    """
    wrapped_lines = wrap(text, max_width)
    for line in wrapped_lines:
        c.drawString(x, y, line)
        y -= line_height
    return y


def generate_pdf(role, round_type, questions, answers, feedbacks, scores):
    file_name = "Interview_Report.pdf"
    c = canvas.Canvas(file_name, pagesize=A4)
    width, height = A4

    # Margins
    left_margin = 40
    right_margin = width - 40
    y = height - 50

    # -----------------------------
    # Header
    # -----------------------------
    c.setFont("Helvetica-Bold", 18)
    c.drawString(left_margin, y, "AI Interview Coach")
    y -= 22

    c.setFont("Helvetica", 12)
    c.drawString(left_margin, y, "Interview Evaluation Report")
    y -= 30

    # Divider
    c.line(left_margin, y, right_margin, y)
    y -= 25

    # -----------------------------
    # Metadata Section
    # -----------------------------
    c.setFont("Helvetica-Bold", 11)
    c.drawString(left_margin, y, "Role:")
    c.setFont("Helvetica", 11)
    c.drawString(left_margin + 60, y, role)
    y -= 18

    c.setFont("Helvetica-Bold", 11)
    c.drawString(left_margin, y, "Interview Round:")
    c.setFont("Helvetica", 11)
    c.drawString(left_margin + 120, y, round_type)
    y -= 18

    c.setFont("Helvetica-Bold", 11)
    c.drawString(left_margin, y, "Date:")
    c.setFont("Helvetica", 11)
    c.drawString(left_margin + 60, y, datetime.now().strftime("%d %B %Y"))
    y -= 30

    # Divider
    c.line(left_margin, y, right_margin, y)
    y -= 25

    # -----------------------------
    # Questions Section
    # -----------------------------
    for i in range(len(questions)):
        if y < 150:
            c.showPage()
            y = height - 50

        # Question
        c.setFont("Helvetica-Bold", 12)
        c.drawString(left_margin, y, f"Question {i + 1}")
        y -= 18

        c.setFont("Helvetica", 11)
        y = draw_wrapped_text(
            c,
            questions[i],
            left_margin,
            y,
            max_width=90,
            line_height=14
        )
        y -= 10

        # Answer
        c.setFont("Helvetica-Bold", 11)
        c.drawString(left_margin, y, "Answer:")
        y -= 15

        c.setFont("Helvetica", 10)
        y = draw_wrapped_text(
            c,
            answers[i],
            left_margin,
            y,
            max_width=95,
            line_height=13
        )
        y -= 10

        # Feedback
        c.setFont("Helvetica-Bold", 11)
        c.drawString(left_margin, y, "Feedback:")
        y -= 15

        c.setFont("Helvetica", 10)
        y = draw_wrapped_text(
            c,
            feedbacks[i],
            left_margin,
            y,
            max_width=95,
            line_height=13
        )
        y -= 10

        # Score
        c.setFont("Helvetica-Bold", 11)
        c.drawString(left_margin, y, f"Score: {scores[i]} / 10")
        y -= 25

        # Section divider
        c.line(left_margin, y, right_margin, y)
        y -= 25

    # -----------------------------
    # Footer
    # -----------------------------
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(
        left_margin,
        30,
        "Generated by AI Interview Coach"
    )

    c.save()
    return file_name