from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from textwrap import wrap
from datetime import datetime


def draw_wrapped_text(c, text, x, y, max_chars, line_height):
    lines = wrap(text, max_chars)
    for line in lines:
        c.drawString(x, y, line)
        y -= line_height
    return y


def generate_pdf(role, round_type, questions, answers, feedbacks, scores, avg_score):

    # -------- Only first 5 questions --------
    questions = questions[:5]
    answers = answers[:5]
    feedbacks = feedbacks[:5]
    scores = scores[:5]

    file_name = "Interview_Report.pdf"
    c = canvas.Canvas(file_name, pagesize=A4)
    width, height = A4

    left = 50
    right = width - 50
    y = height - 60

    # ---------------- HEADER ----------------
    c.setFont("Helvetica-Bold", 22)
    c.drawString(left, y, "AI Interview Coach Report")
    y -= 28

    c.setFont("Helvetica", 12)
    c.drawString(left, y, "Interview Performance Evaluation")
    y -= 30

    c.line(left, y, right, y)
    y -= 25

    # ---------------- SUMMARY ----------------
    c.setFont("Helvetica-Bold", 12)
    c.drawString(left, y, "Role:")
    c.setFont("Helvetica", 12)
    c.drawString(left + 60, y, role)

    c.setFont("Helvetica-Bold", 12)
    c.drawString(left + 300, y, "Round:")
    c.setFont("Helvetica", 12)
    c.drawString(left + 360, y, round_type)
    y -= 20

    c.setFont("Helvetica-Bold", 12)
    c.drawString(left, y, "Date:")
    c.setFont("Helvetica", 12)
    c.drawString(left + 60, y, datetime.now().strftime("%d %B %Y"))

    c.setFont("Helvetica-Bold", 12)
    c.drawString(left + 300, y, "Average Score:")
    c.setFont("Helvetica", 12)
    c.drawString(left + 410, y, f"{avg_score} / 10")
    y -= 20

    c.setFont("Helvetica-Bold", 12)
    c.drawString(left, y, "Total Questions: 5")
    y -= 30

    c.line(left, y, right, y)
    y -= 30

    # ---------------- QUESTIONS ----------------
    for i in range(5):

        if y < 140:
            c.showPage()
            y = height - 60

        # Question
        c.setFont("Helvetica-Bold", 13)
        c.drawString(left, y, f"Question {i+1}")
        y -= 18

        c.setFont("Helvetica", 11)
        y = draw_wrapped_text(c, questions[i], left, y, 95, 14)
        y -= 12

        # Answer
        c.setFont("Helvetica-Bold", 12)
        c.drawString(left, y, "Your Answer:")
        y -= 16

        c.setFont("Helvetica", 10)
        y = draw_wrapped_text(c, answers[i], left, y, 100, 13)
        y -= 12

        # Feedback
        c.setFont("Helvetica-Bold", 12)
        c.drawString(left, y, "AI Feedback:")
        y -= 16

        c.setFont("Helvetica", 10)
        y = draw_wrapped_text(c, feedbacks[i], left, y, 100, 13)
        y -= 12

        # Score
        c.setFont("Helvetica-Bold", 12)
        c.drawString(left, y, f"Score: {scores[i]} / 10")
        y -= 25

        c.line(left, y, right, y)
        y -= 25

    # ---------------- FOOTER ----------------
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(left, 30, "Generated by AI Interview Coach")

    c.save()
    return file_name
